# pruing schedule is used to indicate when performing model compression 
# and the pruning rate
PRUNING: 
    ITERATION: [10, 400, 100]
    COMPRESSION_RATE: [0.5, 0.6, 0.7]
    # after performing mask, how to initialize the remaining weights of network
    INIT_TYPE: 'random'
    # if initializing with random, which kind is used. including kaiming and xavier 
    INIT_KIND: 'kaiming'
    # which kind of pruning, layer or global 
    OPERATION: 'layer' 
    # where to store the last state when pruing network
    DIR: '.running'

# where to run the model, including cuda and cpu
# If the type is cpu, the ids for device don't have any meanings
DEVICE:
    TYPE: 'cuda'
    ID: 2 

# input dataset
DATASET:
    NAME: 'mnist'
    # where to hold the dataset. If not exists, it would download to here.
    DIR: 'data'
    # mean and standard deviation for data preprocessing 
    MEAN: [0.1307]
    DEVIATION: [0.3081]
    TRAIN_BATCHSIZE: 64
    EVAL_BATCHSIZE: 64

# model architecture name
MODEL: 'lenet'

# hyper-paramters for training model
SOLVER:
    LR: 0.01
    GAMMA: 0.7
    OPTIMIZER: 'adam'     # which kind of optimizer method
    STEP_SIZE: 1   # it can be an along number or a list of number
    WEIGHT_DECAY: 0.001
    # the total number of iterations
    TOTAL_EPOCHES: 20 
    # checkpoint-related parameter 
    CHECKPINT:  'checkpoint'
