# pruing schedule is used to indicate when performing model compression 
# and the pruning rate
PRUNING: 
    ITERATION: [90]
    COMPRESSION_RATE: [0.98]
    # after performing mask, how to initialize the remaining weights of network
    INIT_TYPE: 'last'
    # which kind of pruning, layer or global 
    OPERATION: 'layer' 
    # where to store the last state when pruing network
    DIR: '.running'

# where to run the model, including cuda and cpu
# If the type is cpu, the ids for device don't have any meanings
DEVICE:
    TYPE: 'cuda'
    ID: 3

# input dataset
DATASET:
    NAME: 'mnist'
    # where to hold the dataset. If not exists, it would download to here.
    DIR: 'data'
    # mean and standard deviation for data preprocessing 
    MEAN: [0.1307]
    DEVIATION: [0.3081]
    TRAIN_BATCHSIZE: 64
    EVAL_BATCHSIZE: 64

# model architecture name
MODEL: 'fc'

# hyper-paramters for training model
SOLVER:
    LR: 0.01
    GAMMA: 0.1
    OPTIMIZER: 'sgd'     # which kind of optimizer method
    STEP_SIZE: 20   # it can be an along number or a list of number
    WEIGHT_DECAY: 0.001
    MOMENTUM: 0.9
    # the total number of iterations
    TOTAL_EPOCHES: 100 
    # checkpoint-related parameter 
    CHECKPINT:  'checkpoint'
